# Generated by Django 4.1.7 on 2023-03-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
